DROP DATABASE metabeak;
DROP USER metabeak;
CREATE DATABASE metabeak;
CREATE USER metabeak WITH PASSWORD 'metabeak';
GRANT ALL PRIVILEGES ON DATABASE metabeak TO metabeak;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO metabeak;
GRANT ALL PRIVILEGES ON DATABASE metabeak TO metabeak;
